#!/usr/bin/perl -w
my $printer = "m1522";
#my $stampata = "/abd/asc/stampata.ps";
my $stampata = "/abd/asc/tmp/stampa.ps";

#open(PRINTER, "| lpr -P$printer") || die "can't run lpr: $!";
#print "Hello World!\n";
#close(PRINTER) || die "can't close lpr: $!";


#system("cat /abd/asc/stampata.ps| lpr -Pm1522 -h -l -s") or die "cannot do this";
#system("cat /abd/asc/stampata.ps| lpr -Pm1522 -h -l -s");
system("cat $stampata | lpr -P$printer");
