#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per ricevimento file da      *
# Retarus                                  *
#                                          *
# t_retaurs_in                             *
#                                          *
# ---------------------------------------- *
# Versione originale:  001 del 02/03/11    *
#   Ultima revisione:  NdK del 02/03/11    *
# ---------------------------------------- *
#             Autore:  Nicola de Kunovich  *
# ---------------------------------------- *
#                                          *
# In input : (no input)                    *
#                                          *
#------------------------------------------*

#==========================================*
# Moduli Perl                              *
#------------------------------------------*
use MIME::Lite                            ;
use DBI()                                 ;

#==========================================*
# Variabili di connessione                 *
#------------------------------------------*
my $host = '94.199.90.151'                ;
my $user = 'nobili'                       ;
my $pass = '*Na4RcCC)gj%'                 ;

#==========================================*
# Help                                     *
#------------------------------------------*
if (!$host || !$user || $host eq "-help")
{
    print "\n"
        . "Uso :"
        . "\n"
        . "> t_retaurs_in HOST "
        . "USERNAME "
        . "PASSWORD "
        . "\n"
        . "\n"
        . "(C) Copyright - dKb"
        . "\n"
        . "\n"                            ;
    exit()                                ;
}

#==========================================*
# Variabili di comodo                      *
#------------------------------------------*
# my $path = "/productive/ordrsp_in"        ;
# my $path = "/test/from_nobili/invoic_in"    ;
my $path = "/test/to_nobili/orders_in"        ;

#==========================================*
# Parametri di connessione al database     *
#------------------------------------------*
my $dhst = "localhost"                    ;
my $dusr = "root"                         ;
my $dpwd = "loppio2"                      ;
my $dtbs = "nob"                          ;
my $dtab = "retarus"                      ;

#==========================================*
# Parametri di posta                       *
#------------------------------------------*
$isps = "mail.protec.it"                  ;
my $mitt = 'dkb@dkb.it'                   ;
my $dest = 'dkb@dkb.it'                   ;
my $desb = 'dkb@dkb.it'                   ;

#==========================================*
# Connessione database                     *
#------------------------------------------*
my $dbh = DBI->connect("DBI:"
                     . "mysql:database="
                     . "$dtbs;host=$dhst",
                       $dusr,
                       $dpwd,
                      {RaiseError => 1,
                       PrintError => 0})  ;
#==========================================*
# Connessione FTP                          *
#------------------------------------------*

#==========================================*
# Login                                    *
#------------------------------------------*

#==========================================*
# Directory di input                       *
#------------------------------------------*
my $elemento = "ORDERS_11_21254492.CSV.OK";

#==========================================*
# Recupero dei file remoti                 *
#------------------------------------------*
    #--------------------------------------*
    # Lettura elemento                     *
    #--------------------------------------*
    my $sel = "SELECT path
                      FROM "
                    . $dtab
                    . " WHERE path = '"
                    . $elemento
                    . "' AND  flag = ''"  ;
    my $sth = $dbh->prepare($sel)         ;
                      
    #--------------------------------------*
    # Esecuzione                           *
    #--------------------------------------*
    $sth->execute()                       ;

    #--------------------------------------*
    # Test su esito lettura                *
    #--------------------------------------*
    $row = $sth->rows                     ;

    #--------------------------------------*
    # Record non trovati                   *
    #--------------------------------------*
    if ($row == 1)
    {
        #----------------------------------*
        # Determinazione numero documento  *
        #----------------------------------*
#        my @numr = split(/,/, &det_num($elemento));
#        my $rnum = $numr[7]         ;

        print   "\n";      
        print   $elemento;      
        print   "\n";      
        
        #----------------------------------*
        # Messaggio di posta               *
        #----------------------------------*
        &messaggio($elemento, $rnum)      ;
    }
    #--------------------------------------*
    # Fine ciclo di lettura                *
    #--------------------------------------*

#==========================================*
# Uscita da FTP                            *
#------------------------------------------*

#==========================================*
# Disconnessione dal database              *
#------------------------------------------*

#=========================================*
# Trattamento messaggio di posta          *
#-----------------------------------------*
sub messaggio 
{
    #--------------------------------------*
    # Estrazione del fornitore dal nome    *
    # file                                 *
    #--------------------------------------*
    my $forn = "PADIS"                    ;

    #--------------------------------------*
    # Composizione soggetto                *
    #--------------------------------------*
    my $subj = "Conferma ordine da "
             . $forn
             . " "
             . $rnum                      ;
    #--------------------------------------*
    # Messaggio di posta                   *
    #--------------------------------------*
    $msg = MIME::Lite->new(
           From     =>$mitt,
           To       =>$dest,
           Bcc      =>$desb,
           Subject  =>$subj,
           Data     =>"Conferma "
                    . $elemento
                    . " da "
                    . $forn
                    . " "
                    . $rnum)              ;
    #--------------------------------------*
    # Invio                                *
    #--------------------------------------*
    $msg->send('smtp', $isps, Timeout=>60);
}

#=========================================*
# Determinazione numero di riferimento    *
#-----------------------------------------*
sub det_num 
{
    #--------------------------------------*
    # Filename                             *
    #--------------------------------------*
    my $filn = "/abd/asc/imp/" . $elemento ;
    #--------------------------------------*
    # Open file                            *
    #--------------------------------------*
    open (CONFERMA, $filn)                ;
    #--------------------------------------*
    # Estrazione I riga                    *
    #--------------------------------------*
    my $trow = ''                         ;
    if (<CONFERMA>)
    {
        $trow=<CONFERMA>                  ;
    }
    return $trow                          ;
    #--------------------------------------*
    # Close file                           *
    #--------------------------------------*
    close CONFERMA                        ;
}
