#!/usr/bin/perl -w

use XML::Parser;
  
  $file = shift;
  
  $p1 = new XML::Parser(Style => 'Debug');
$record =  $p1->parsefile($file);
#  $p1->parse('<foo id="me">Hello World</foo>');


open (OUTFILE, ">/abd/asc/tmp/parse_xml_5_prv.log") or die
         "Impossibile aprire il file"               ;

        print OUTFILE $record . "\n";




close (OUTFILE)                                                ;

