#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per ricevimento file da      *
# Retarus                                  *
#                                          *
# t_retaurs_in                             *
#                                          *
# ---------------------------------------- *
# Versione originale:  001 del 13/04/07    *
#   Ultima revisione:  NdK del 06/02/10    *
# ---------------------------------------- *
#             Autore:  Nicola de Kunovich  *
# ---------------------------------------- *
#                                          *
# In input : (no input)                    *
#                                          *
#------------------------------------------*

#==========================================*
# Moduli Perl                              *
#------------------------------------------*

use MIME::Lite                            ;
use DBI()                                 ;

#==========================================*
# Variabili di connessione                 *
#------------------------------------------*
my $host = '82.135.18.189'                ;
# my $host = '94.199.90.151'                ;
my $user = 'siri'                         ;
my $pass = 'siri2retarus%%'               ;

#==========================================*
# Help                                     *
#------------------------------------------*
if (!$host || !$user || $host eq "-help")
{
    print "\n"
        . "Uso :"
        . "\n"
        . "> t_retaurs_in HOST "
        . "USERNAME "
        . "PASSWORD "
        . "\n"
        . "\n"
        . "(C) Copyright - dKb"
        . "\n"
        . "\n"                            ;
    exit()                                ;
}

#==========================================*
# Variabili di comodo                      *
#------------------------------------------*
my $path = "/productive/ordrsp_in"        ;
# my $path = "/test/ordrsp_in"            ;

#==========================================*
# Parametri di connessione al database     *
#------------------------------------------*
my $dhst = "localhost"                    ;
my $dusr = "root"                         ;
my $dpwd = "loppio2"                      ;
my $dtbs = "siri"                         ;
my $dtab = "retarus"                      ;

#==========================================*
# Parametri di posta                       *
#------------------------------------------*
$isps = "mail.protec.it"                  ;
my $mitt = 'dkb@dkb.it'                   ;
my $dest = 'dkb@dkb.it'                   ;
my $desb = 'dkb@dkb.it'                   ;

#==========================================*
# Connessione database                     *
#------------------------------------------*
my $dbh = DBI->connect("DBI:"
                     . "mysql:database="
                     . "$dtbs;host=$dhst",
                       $dusr,
                       $dpwd,
                      {RaiseError => 1,
                       PrintError => 0})  ;
#==========================================*
# Connessione FTP                          *
#------------------------------------------*

#==========================================*
# Login                                    *
#------------------------------------------*

#==========================================*
# Directory di input                       *
#------------------------------------------*

my $elemento = "RSP_VIS_20070625_A001B0IQ.CSV";


#==========================================*
# Recupero dei file remoti                 *
#------------------------------------------*
    #--------------------------------------*
    # Lettura elemento                     *
    #--------------------------------------*
    my $sel = "SELECT path
                      FROM "
                    . $dtab
                    . " WHERE path = '"
                    . $elemento
                    . "' AND  flag = ''"  ;
    my $sth = $dbh->prepare($sel)         ;
                      
    #--------------------------------------*
    # Esecuzione                           *
    #--------------------------------------*
    $sth->execute()                       ;

    #--------------------------------------*
    # Test su esito lettura                *
    #--------------------------------------*
    $row = $sth->rows                     ;

    #--------------------------------------*
    # Record non trovati                   *
    #--------------------------------------*
    if ($row == 1)
    {
        #----------------------------------*
        # Determinazione numero documento  *
        #----------------------------------*
        my @numr = split(/,/, &det_num($elemento));

        my $rnum = $numr[7]         ;
        
        print   "\n";      
        print   $rnum;      
        print   "\n";      
        
        #----------------------------------*
        # Messaggio di posta               *
        #----------------------------------*
        &messaggio($elemento, $rnum)      ;
    }
    #--------------------------------------*
    # Fine ciclo di lettura                *
    #--------------------------------------*

#==========================================*
# Uscita da FTP                            *
#------------------------------------------*

#==========================================*
# Disconnessione dal database              *
#------------------------------------------*

#=========================================*
# Trattamento messaggio di posta          *
#-----------------------------------------*
sub messaggio 
{
    #--------------------------------------*
    # Estrazione del fornitore dal nome    *
    # file                                 *
    #--------------------------------------*
    my $forn = ""                         ;
    my $wfor = substr($elemento, 4, 3)           ;
    
    if ($wfor eq "VIS")
    {
        $forn = "Vishay"                  ;
    }
     else
    {
        $forn = "Yageo"                   ;
    }
    #--------------------------------------*
    # Composizione soggetto                *
    #--------------------------------------*
    my $subj = "Conferma ordine da "
             . $forn
             . " "
             . $rnum                      ;
    #--------------------------------------*
    # Messaggio di posta                   *
    #--------------------------------------*
    $msg = MIME::Lite->new(
           From     =>$mitt,
           To       =>$dest,
           Bcc      =>$desb,
           Subject  =>$subj,
           Data     =>"Conferma "
                    . $elemento
                    . " da "
                    . $forn
                    . " "
                    . $rnum)              ;
    #--------------------------------------*
    # Invio                                *
    #--------------------------------------*
    $msg->send('smtp', $isps, Timeout=>60);
}

#=========================================*
# Determinazione numero di riferimento    *
#-----------------------------------------*
sub det_num 
{
    #--------------------------------------*
    # Filename                             *
    #--------------------------------------*
    my $filn = "/abd/asc/imp/" . $elemento ;
    #--------------------------------------*
    # Open file                            *
    #--------------------------------------*
    open (CONFERMA, $filn)                 ;
    #--------------------------------------*
    # Estrazione I riga                    *
    #--------------------------------------*
    if (<CONFERMA>)
    {
    my $trow=<CONFERMA>                   ;
    }
    return $trow                          ;
    #--------------------------------------*
    # Close file                           *
    #--------------------------------------*
    close CONFERMA                        ;
}
