#!/usr/bin/perl -w
#==========================================*
# Modulo Perl di invio posta con autenti-  *
# cazione TLS                              *
#                                          *
# t_sender_tls TEST                        *
#                                          *
#------------------------------------------*

use Net::SMTP::TLS;  
 
#
my $mailer = new Net::SMTP::TLS(  
    'siriel-com01b.mail.protection.outlook.com',
    Port    =>      25,  
    Hello   =>      '',
    User    =>      'siri-el',
    Password=>      'SIR-iel_71',
    Debug   => 1) || die "Connessione fallita al server smtp";
 
$mailer->mail('info@siri-el.com');
$mailer->to('wip@wip-info.it');
$mailer->data;  
$mailer->datasend("\n");  
$mailer->datasend("Inviato da Perl!");  
$mailer->dataend;  
$mailer->quit;
