#!/usr/bin/perl -w
#==========================================*
# Modulo Perl di invio posta con autenti-  *
# cazione SSL                              *
#                                          *
# t_sender_ssl TEST                        *
#                                          *
#------------------------------------------*

use Net::SMTP::SSL                        ;
use Test::SMTP;
 
plan tests => 10;
# Constructors
my $client1 = Test::SMTP->connect_ok('connect to mailhost',
                                     Host => '127.0.0.1', AutoHello => 1);
$client1->mail_from_ok('test@example.com', 'Accept an example mail from');
$client1->rcpt_to_ko('test2@example.com', 'Reject an example domain in rcpt to');
$client1->quit_ok('Quit OK');
my $client2 = Test::SMTP->connect_ok('connect to mailhost',
                                     Host => '127.0.0.1', AutoHello => 1);
...



exit();


#==========================================*
# Moduli Perl utilizzati                   *
#------------------------------------------*

my $srvr = 'server.pec-email.com';
my $user = 'elettra@pec.elettra.it';
my $pass = 'Pwd_elettra';
my $mitt = 'elettra@pec.elettra.it';
my $dest = 'wip@gigapec.it';
my $testo = 'CONTENUTO MESSAGGIO';

    #--------------------------------------*
    # Normalizzazione preliminare          *
    #--------------------------------------*
    my $smtp                              ;

    #--------------------------------------*
    # Invio vero e proprio                 *
    #--------------------------------------*
    if (not $smtp = Net::SMTP::SSL->new($srvr,
                              Port => 465,
                              Debug => 1))
       {
           die "Connessione al server "
             . "fallita\n"                ;
       }

    #--------------------------------------*
    # Autenticazione                       *
    #--------------------------------------*
    $smtp->auth($user, $pass)
     || die "Autenticazione fallita!\n"   ;

    $smtp->mail($mitt)                    ;
    $smtp->to($dest)                      ;
    $smtp->data();
    $smtp->datasend("To: " . $dest . "\n")  ;
    $smtp->datasend("Subject: PROVA\n")   ;

    #--------------------------------------*
    # Chiusura invio                       *
    #--------------------------------------*
    $smtp->datasend("\n")                 ;
    $smtp->datasend("Content-Type: text/html; charset=UTF-8\n\n");
    $smtp->datasend($testo . "\n")        ;
    $smtp->dataend()                      ;
    $smtp->quit                           ;
