#!/usr/bin/perl -w
use File::Basename                        ;


        my @time = stat($fil)             ;            
        my $tim = $time[9]                ;            
        
        
        
        my $aaa = 1900+(localtime($tim))[5];
        my $mmm = (localtime($tim))[4]    ;
        my $ggg = (localtime($tim))[3]    ;
        #----------------------------------*
        my $ann = sprintf ("%04d",$aaa)   ;
        my $mes = sprintf ("%02d",$mmm+1) ;
        my $gio = sprintf ("%02d",$ggg)   ;
        #----------------------------------*
        my $upd  = $ann . "-"
                        . $mes
                        . "-"
                        . $gio           ;


print $upd;
exit ();

