#!/bin/bash
#
#if [ -n "$(find /abd/tmp -prune -empty -type d 2>/dev/null)" ]
#then
#  echo "empty directory"
#else
#  echo "contains files (or does not exist or is not a directory)"
#fi

files=$(shopt -s nullglob dotglob; echo $1/*)
if (( ${#files} ))
then
  echo "contains files"
else 
  echo "empty (or does not exist or is a file)"
fi