#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per creare sottocartelle     *
# in ASC per l'anno nuovo                  *
#                                          *
# t_asc_ann_NEW                            *
#                                          *
# ---------------------------------------- *
# Versione originale:  001 del 11/01/2022  *
#   Ultima revisione:  NdK del 16/01/2025  *
# ---------------------------------------- *
#             Autore:  Nicola de Kunovich  *
# ---------------------------------------- *
#                                          *
# In input       : - Anno (9999)           *
#                                          *
# (Configurazione: - 't_asc_ann_NEW.ini'   *
#                                          *
# CRONTAB        : - 0  0  12 1 *          *
#                                          *
# PROMEMORIA     : - Manca 'slc' !!!       *
#                                          *
#==========================================*

#==========================================*
# Valori in input                          *
#------------------------------------------*
my $ann_new = shift                       ;

#==========================================*
# Se anno vuoto: default anno successivo a *
#                quello in corso           *
#------------------------------------------*
if (!$ann_new || $ann_new eq "")
{
    my $ann = (localtime)[5]              ;
    my $anu = int($ann)                   ;
       $anu = $anu + 1901                 ;
       $ann_new = sprintf ("%04d",$anu)   ;
}

#==========================================*
# Variabili definite                       *
#------------------------------------------*
#------------------------------------------*
# Directory di configurazione base         *
#------------------------------------------*
my $cfg_bas = "/abd/asc/cfg/"
            . "t_asc_ann_NEW.ini"         ;
#
my %cnf_ele = do $cfg_bas                 ;
my $bas_dir = $cnf_ele{bas_dir}           ;
my $cod_azi = $cnf_ele{cod_azi}           ;
my $azi_dir = $bas_dir
            . $cod_azi
            . "/"                         ;

#==========================================*
# DEBUG                                    *
#------------------------------------------*
# print "bas_dir = " . $bas_dir . "\n"    ;
# print "cod_azi = " . $cod_azi . "\n"    ;
# print "azi_dir = " . $azi_dir . "\n"    ;
# exit()                                  ;

#==========================================*
# Normalizzazioni                          *
#------------------------------------------*
my $nam_new = ""                          ;
my $sub_new = ""                          ;
my $dir_001 = ""                          ;
my $dir_002 = ""                          ;
my $dir_003 = ""                          ;

#==========================================*
# Directory 'est'                          *
#------------------------------------------*
# Sub-sub-directory 'est/arc/ANNO'         *
#------------------------------------------*
$dir_001 = "est"                          ;
$dir_002 = "arc"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;
#------------------------------------------*
# Sub-sub-directory 'est/xml/ANNO'         *
#------------------------------------------*
$dir_001 = "est"                          ;
$dir_002 = "xml"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;
#------------------------------------------*
# Sub-sub-directory 'est/dst/ANNO'         *
#------------------------------------------*
$dir_001 = "est"                          ;
$dir_002 = "dst"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;

#==========================================*
# Directory 'fat'                          *
#------------------------------------------*
# Sub-sub-directory 'fat/arc/ANNO'         *
#------------------------------------------*
$dir_001 = "fat"                          ;
$dir_002 = "arc"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;
#------------------------------------------*
# Sub-sub-directory 'fat/xml/ANNO'         *
#------------------------------------------*
$dir_001 = "fat"                          ;
$dir_002 = "xml"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;
#------------------------------------------*
# Sub-sub-directory 'fat/dst/ANNO'         *
#------------------------------------------*
$dir_001 = "fat"                          ;
$dir_002 = "dst"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;

#==========================================*
# Directory 'scf'                          *
#------------------------------------------*
# Sub-sub-directory 'scf/imp/ANNO'         *
#------------------------------------------*
$dir_001 = "scf"                          ;
$dir_002 = "imp"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;
#------------------------------------------*
# Sub-sub-directory 'scf/att/ANNO'         *
#------------------------------------------*
$dir_001 = "scf"                          ;
$dir_002 = "att"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;
#------------------------------------------*
# Sub-sub-directory 'scf/htm/ANNO'         *
#------------------------------------------*
$dir_001 = "scf"                          ;
$dir_002 = "htm"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;
#------------------------------------------*
# Sub-sub-directory 'scf/dst/ANNO'         *
#------------------------------------------*
$dir_001 = "scf"                          ;
$dir_002 = "dst"                          ;
$dir_003 = $ann_new                       ;
&mak_dir($dir_001, $dir_002, $dir_003)    ;

#------------------------------------------*
# Fine script                              *
#==========================================*

#==========================================*
# SUBROUTINES                              *
#==========================================*

#==========================================*
# Subroutine di creazione                  *
#------------------------------------------*
sub mak_dir 
{
    #--------------------------------------*
    # Valori in input                      *
    #--------------------------------------*
    my $inp_001 = shift                   ;
    my $inp_002 = shift                   ;
    my $inp_003 = shift                   ;
    #--------------------------------------*
    # Normalizzazioni                      *
    #--------------------------------------*
    my $dir_new = ""                      ;
    my $sep_002 = ""                      ;
    my $sep_003 = ""                      ;
    #--------------------------------------*
    # Eventuali barre                      *
    #--------------------------------------*
    if ($inp_002 ne ""){$sep_002 = "/"}   ;
    if ($inp_003 ne ""){$sep_003 = "/"}   ;
    #--------------------------------------*
    # Preparazione directory               *
    #--------------------------------------*
    $dir_new = $azi_dir
             . $inp_001
             . $sep_002
             . $inp_002
             . $sep_003
             . $inp_003                   ;
    #--------------------------------------*
    # Creazione                            *
    #--------------------------------------*
    eval {mkdir($dir_new)}                ;
    if ($@)
    {
        print "Non posso creare la cartella $dir_new: $@";
    }
    #--------------------------------------*
    # Privilegi                            *
    #--------------------------------------*
    chmod(0775, $dir_new) or
          die "Fallito chmod di $dir_new: $!";
}






