#!/usr/bin/perl -w
#=========================================*
# Modulo Perl per decodificare un base64  *
#                                         *
# FUNZIONA! - 29/11/2018                  *
#=========================================*

use MIME::Base64 qw(decode_base64);

my $b64 = shift;
my $dec = $b64 . '.dec'                   ;

#=========================================*
# Open del file di input                  *
#-----------------------------------------*
open(FILE, $b64) or die "$!"              ;

#=========================================*
# Open del file di output                 *
#-----------------------------------------*
open (OUTFILE, ">$dec") or die
     "Impossibile aprire il file di output";

binmode OUTFILE;

my $buf;

var base64Rejex = /^(?:[A-Z0-9+\/]{4})*(?:[A-Z0-9+\/]{2}==|[A-Z0-9+\/]{3}=|[A-Z0-9+\/]{4})$/i;
var isBase64Valid = base64Rejex.test(base64Data);

if (isBase64Valid) {
    // true if base64 formate
    console.log('It is base64');
} else {
    // false if not in base64 formate
    console.log('it is not in base64');
}

while ( $buf = <FILE> ) {
    print OUTFILE decode_base64( $buf );
}








#=========================================*
# Close del file di input                 *
#-----------------------------------------*
close (FILE)                             ;

#=========================================*
# Close del file di output                *
#-----------------------------------------*
close (OUTFILE)                           ;
