#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per trasformare in 'HTML'    *
# un file 'CSV' separato da ';'            *
#                                          *
# Nome del modulo: t_csv2html              *
#                                          *
# N.B.: Utilizzato dal modulo 'mxport'     *
#                                          *
#       ___ NON PIU' ___                   *
#                                          *
#       ___ Ma funziona bene ___           *
#                                          *
# ---------------------------------------- *
# Versione originale:   001 del 27/01/2022 *
#   Ultima revisione:   wip del 02/02/2022 *
# ---------------------------------------- *
#             Autore:   Nicola de Kunovich *
# ---------------------------------------- *
#                                          *
# In input       : - pathname file CSV     *
#                                          *
#==========================================*

#==========================================*
# Moduli Perl utilizzati                   *
#==========================================*
use File::Basename                        ;
use Unicode::Normalize                    ;
use Text::CSV                             ;
   
#==========================================*
# Valori in input                          *
#------------------------------------------*
my $pth_csv = shift or die                ;
#------------------------------------------*
# Estrazione nome file                     *
#------------------------------------------*
(my $fil_nam,
 my $fil_pat,
 my $fil_ext) = fileparse($pth_csv, qr/\.[^.]*/);
#------------------------------------------*
# Pathname file di output                  *
#------------------------------------------*
$pth_htm = $fil_pat
         . $fil_nam
         . ".html"                        ;
#------------------------------------------*
# Intestazione colonne                     *
#------------------------------------------*
my @col_swc = ()                          ;
#------------------------------------------*
# Parametri di lettura 'CSV'               *
#------------------------------------------*
my $csv_prs = Text::CSV->new
({    binary => 1,
   auto_diag => 1,
  quote_char => undef,
 escape_char => undef,    
    sep_char => ';'
})                                        ;

#------------------------------------------*
# Open file 'CSV'                          *
#------------------------------------------*
open(my $iof_csv, '<:encoding(utf8)', $pth_csv) or die
        "Impossibile aprire '$pth_csv'"   ;
#------------------------------------------*
# Open file 'HTML'                         *
#------------------------------------------*
open(my $iof_htm, '>', $pth_htm) or die
        "Impossibile aprire '$pth_htm'"   ;

#------------------------------------------*
# Intestazione pagina HTML                 *
#------------------------------------------*
&opn_web ($fil_nam)                       ;
#------------------------------------------*
# Normalizazioni                           *
#------------------------------------------*
my $row_csv = ""                          ;
my $row_num = 0                           ;
my $col_num = 0                           ;
#------------------------------------------*
# Switch per allineamento colonne          *
#------------------------------------------*
&pre_swc                                  ;
&wrt_ind ("</thead>")                     ;
&wrt_ind ("<tbody>")                      ;

#------------------------------------------*
# Ciclo di scansione                       *
#------------------------------------------*
while (my $row = $csv_prs->getline($iof_csv))
{
    #--------------------------------------*
    # Apertura riga                        *
    #--------------------------------------*
    &wrt_ind ("<tr>")                     ;
    #--------------------------------------*
    # Incremento contatore colonne         *
    #--------------------------------------*
    $row_num++                            ;
    #--------------------------------------*
    # Contatore colonne                    *
    #--------------------------------------*
    &wrt_ind ("<td align=right>" 
            . $row_num . "</td>")         ;
    #--------------------------------------*
    # Ciclo per le righe corpo             *
    #--------------------------------------*
    $col_num = 0                          ;
    foreach $row_csv (@$row)
    {
        #----------------------------------*
        # Pulizia preliminare riga         *
        #----------------------------------*
        my $rig_wrk = ""                  ;
           $rig_wrk = $row_csv            ;
           $rig_wrk = &pul_str($row_csv)  ;
        #----------------------------------*
        # Incremento contatore colonne     *
        #----------------------------------*
        $col_num++                        ;
        #----------------------------------*
        # Test su switch di allineamento   *
        #----------------------------------*
        if ($col_swc[$col_num] eq "R")
        {
            #------------------------------*
            # Allineamento a destra        *
            #------------------------------*
            &wrt_ind ("<td align=right>"
                    . $rig_wrk
                    . "</td>")            ;
            #------------------------------*
            # DEBUG                        *
            #------------------------------*
            # print $rig_wrk . "\n"       ;
        }
         else
        {
            #------------------------------*
            # Allineamento standard        *
            #------------------------------*
            &wrt_ind ("<td>"
                    . $rig_wrk
                    . "</td>")            ;
            #------------------------------*
            # DEBUG                        *
            #------------------------------*
            # print $rig_wrk . "\n"       ;
        }
    }
    #--------------------------------------*
    # Chiusura riga                        *
    #--------------------------------------*
    &wrt_ind ("</tr>")                    ;
}

#------------------------------------------*
# Chiusura pagina HTML                     *
#------------------------------------------*
&cls_web                                  ;
#------------------------------------------*
# Close file di input                      *
#------------------------------------------*
close $iof_csv                            ;
#------------------------------------------*
# Close file di output                     *
#------------------------------------------*
close $iof_htm                            ;
#------------------------------------------*
# Cambio privilegi del file generato       *
#------------------------------------------*
chmod(0666, $pth_htm) or
      die "Fallito chmod di $pth_htm: $!" ;

#==========================================*
# SUBROUTINES                              *
#==========================================*

#==========================================*
# Intestazione pagina HTML                 *
#------------------------------------------*
sub opn_web
{
    #--------------------------------------*
    # Titolo in input                      *
    #--------------------------------------*
    my $wrk_nam = shift                   ;
    #--------------------------------------*
    # Pagina HTML                          *
    #--------------------------------------*
    &wrt_ind ("<!DOCTYPE html>")          ;
    &wrt_ind ("<html>")                   ;
    &wrt_ind ("<head>")                   ;
    &wrt_ind ("<title>"
             . $fil_nam
             . "</title>")                ;
    #--------------------------------------*
    # CSS                                  *
    #--------------------------------------*
    &wrt_ind ("<link rel='stylesheet' "
            . "href='../tmp/"
            . "css/theme.blue.css'>")     ;
    #--------------------------------------*
    # Javascript                           *
    #--------------------------------------*
    &wrt_ind ("<script src='../tmp/jsc/"
            . "jquery.min.js'>"
            . "</script>")                ;
    &wrt_ind ("<script src='../tmp/jsc/"
            . "jquery.tablesorter"
            . ".js'></script>")           ;
    &wrt_ind ("<script src='../tmp/jsc/"
            . "tan_sort.js'>"
            . "</script>")                ;
    #--------------------------------------*
    # Chiusura testata                     *
    #--------------------------------------*
    &wrt_ind ("</head>")                  ;
    &wrt_ind ("<body>")                   ;
    &wrt_ind ("<center>")                 ;
    &wrt_ind ("<table class='table2'>")   ;
    &wrt_ind ("<thead>")                  ;
}

#==========================================*
# Chiusura pagina HTML                     *
#------------------------------------------*
sub cls_web
{
    #--------------------------------------*
    # Chiusura 'index.html'                *
    #--------------------------------------*
    &wrt_ind ("</tbody>")                 ;
    &wrt_ind ("</table>")                 ;
    &wrt_ind ("</center>")                ;
    &wrt_ind ("<br>")                     ;
    &wrt_ind ("<center>")                 ;
    &wrt_ind ("<address>")                ;
    &wrt_ind ("<font size=3>&copy "
            . "TANGRAM - wip")            ;
    &wrt_ind ("</font>")                  ;
    &wrt_ind ("</address>")               ;
    &wrt_ind ("</center>")                ;
    &wrt_ind ("</body>")                  ;
    &wrt_ind ("</html>")                  ;
}

#==========================================*
# Scrittura su file 'index.html'           *
#------------------------------------------*
sub wrt_ind
{
    #--------------------------------------*
    # Stringa in input                     *
    #--------------------------------------*
    my $str_wrt = shift                   ;
    #--------------------------------------*
    # Scrittura                            *
    #--------------------------------------*
    print $iof_htm $str_wrt . "\n"         ;
}

#==========================================*
# Pulizia stringhe                         *
#------------------------------------------*
sub pul_str
{
    #--------------------------------------*
    # Valori in input                      *
    #--------------------------------------*
    my $wrk_str = ""                      ;
       $wrk_str = shift                   ;
    #--------------------------------------*
    # Pulizia caratteri accentati          *
    #--------------------------------------*
    $wrk_str = NFKD($wrk_str)             ;
    $wrk_str =~ s/\p{NonspacingMark}//g   ;
    #--------------------------------------*
    # Eliminazione eventuali caratteri     *
    # strani                               *
    #--------------------------------------*
    $wrk_str=~s/[^\x00-\x7f]//g           ;
    #--------------------------------------*
    # Eliminazione spazi superflui valore  *
    #--------------------------------------*
#    $wrk_str =~ s/^\s+|\s+$//g            ;
    
#    $wrk_str =~ s/ +/ /                   ;
    
    $wrk_str =~ tr/ //s;    
      
    #--------------------------------------*
    # Valore restituito                    *
    #======================================*
    return $wrk_str                       ;
}

#==========================================*
# Preparazione switch per allineamento     *
# colonne                                  *
#------------------------------------------*
sub pre_swc
{
    #--------------------------------------*
    # Header del file CSV                  *
    #--------------------------------------*
    my $hea_der = $csv_prs->getline ($iof_csv);
    #--------------------------------------*
    # Numero di colonne                    *
    #--------------------------------------*
    my $max_col = scalar @$hea_der        ;
    #--------------------------------------*
    # Apertura riga                        *
    #--------------------------------------*
    &wrt_ind ("<tr>")                     ;
    #--------------------------------------*
    # Colonna per progressivo              *
    #--------------------------------------*
    &wrt_ind ("<th>NR</th>")              ;
    #--------------------------------------*
    # Ciclo di scansione intestazioni      *
    #--------------------------------------*
    for (my $i = 0; $i < scalar(@$hea_der); $i++)
    {
        #----------------------------------*
        # Test se presenti parentesi '{}'  *
        #----------------------------------*
        my $rig_csv = @$hea_der[$i]       ;
        my $res_ult = $rig_csv=~ /\{/g    ;
        #----------------------------------*
        # Incremento contatore colonne     *
        #----------------------------------*
        $col_num++                        ;
        #----------------------------------*
        # Test se trovate parentesi '{}'   *
        #----------------------------------*
        if ($res_ult > 0)
        {
            #------------------------------*
            # Switch allineamento a destra *
            #------------------------------*
            $col_swc[$col_num] = "R"      ;
            #------------------------------*
            # Pulizia delle parentesi      *
            #------------------------------*
            $rig_csv =~ s/{//             ;
            $rig_csv =~ s/}//             ;
            #------------------------------*
            # Colonna di valori            *
            #------------------------------*
            &wrt_ind ("<th class='sorter"
                    . "-thousands'>"
                    . $rig_csv
                    . "</th>")            ;
        }
         else
        {
            #------------------------------*
            # Switch allineamento a sin.   *
            #------------------------------*
            $col_swc[$col_num] = "L"      ;
            #------------------------------*
            # Colonna di valori            *
            #------------------------------*
            &wrt_ind ("<th>"
                    . $rig_csv
                    . "</th>")            ;
        }
    }
    #--------------------------------------*
    # Chiusura riga                        *
    #--------------------------------------*
    &wrt_ind ("</tr>")                    ;
}

