#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per inviare il file prepara- *
# to al sito Web del corriere BRT          *
# corriere BRT                             *
#                                          *
# t_ele_brt_upl                            *
#                                          *
# N.B.: Utilizzato da '________'           *
#                                          *
# SU MISURA PER ELETTRA                    *
#                                          *
# ___ MAI PROVATO E UTILIZZATO             *
#                                          *
# ---------------------------------------- *
# Versione originale:  001 del 26/07/22    *
#   Ultima revisione:  NdK del 26/07/22    *
# ---------------------------------------- *
#             Autore:  Nicola de Kunovich  *
# ---------------------------------------- *
#                                          *
# In input       : (nessun input)          *
#                                          *
#------------------------------------------*

#==========================================*
# Moduli Perl utilizzati                   *
#------------------------------------------*
use strict                                ;
use WWW::Mechanize                        ;
use HTTP::Cookies                         ;

#==========================================*
# Variabili autenticazione 'https'         *
#------------------------------------------*
my $user = "Elettra"                      ;
my $pass = "password"                     ;

#==========================================*
# Variabili statiche                       *
#------------------------------------------*
# URL di autenticazione                    *
#------------------------------------------*
my $urla = "https://services.brt.it/it/"
         . "area-clienti"                 ;
#------------------------------------------*
# URL di upload                            *
#------------------------------------------*
my $urlp = "getimage?class=de.florissima."
         . "data.erp.items.FlArtikel&id=" ;

#==========================================*
# Inizio comunicazione 'https'             *
#------------------------------------------*
my $mech = WWW::Mechanize->new()             ;
$mech->cookie_jar(HTTP::Cookies->new())   ;
$mech->get($urla)                         ;
#------------------------------------------*
# Login                                    *
#------------------------------------------*
$mech->submit_form(
    form_id     => 'login',
    fields      => {
        usrname     => $user,
        password    => $pass,
    }
);






# $mech->form_id('login')                   ;
# $mech->field(usrname => $user)            ;
# $mech->field(password => $pass)         ;
# $mech->click()                            ;

# print $mech->content                      ;



#==========================================*
# SUB-ROUTINES                             *
#==========================================*

