#!/usr/bin/perl -w
#==========================================*
# Modulo Perl client INAP per accounts PEC *
#                                          *
# t_mail_imap                              *
#                                          *
# ---------------------------------------- *
# Versione originale:   001 del 01/02/19   *
#   Ultima revisione:   wip del 04/02/19   *
# ---------------------------------------- *
#             Autore:   Nicola de Kunovich *
# ---------------------------------------- *
#                                          *
# In input : (no input)                    *
#                                          *
#==========================================*

#==========================================*
# Moduli Perl                              *
#------------------------------------------*
use Net::POP3S                            ;
use Mail::IMAPClient                      ;
use IO::Socket::SSL                       ;

#==========================================*
# Debug opzionale                          *
#------------------------------------------*
my $deb_bug = shift                       ;
if (!$deb_bug){$deb_bug = 0}              ;

#==========================================*
# File di configurazione                   *
#------------------------------------------*
my $cfg_bas = "/abd/asc/cfg/"             ;
my $cfg_fil = $cfg_bas
            . "t_mail_pop3s.ini"          ;
my %cnf_ele = do $cfg_fil                 ;
#------------------------------------------*
# Files e cartelle di appoggio             *
#------------------------------------------*
my $pec_buf = $cnf_ele{pec_buf}           ;
my $att_dir = $cnf_ele{att_dir}           ;
my $log_fil = $cnf_ele{log_fil}           ;
#------------------------------------------*
# Parametri account                        *
#------------------------------------------*
my $pop_srv = $cnf_ele{pop_srv}           ;
my $usr_srv = $cnf_ele{usr_srv}           ;
my $pwd_srv = $cnf_ele{pwd_srv}           ;
my $ssl_prm = 'ssl'                       ;

#==========================================*
# Connessione                              *
#------------------------------------------*
my $con_ima = IO::Socket::SSL->new(
   PeerAddr => 'imaps.pec.aruba.it',
   PeerPort => 993,
  )
 or die("ERRORE: Connessione non riuscita.\n");

#==========================================*
# Login                                    *
#------------------------------------------*
my $client = Mail::IMAPClient->new(
   Socket   => $con_ima,
   User     => $usr_srv,
   Password => $pwd_srv,
   IgnoreSizeErrors => '1'
  )
 or die("ERRORE: Login non riuscito.\n")  ;

my $num_msg = $client->unseen_count||'0';


if ($client->IsAuthenticated())
{

    $client->select('INBOX');



    print $num_msg . "\n";
}

#==========================================*
# Se zero messaggi: uscita                 *
#------------------------------------------*
if ($num_msg == 0)
{
    exit()                                ;
}

#==========================================*
# Inizializzazione parser                  *
#------------------------------------------*
my $par_ser=new MIME::Parser              ; 
$par_ser->ignore_errors(1)                ; 
$par_ser->extract_uuencode(1)             ; 
$par_ser->tmp_recycling(0)                ; 
$par_ser->output_to_core(1)               ; 

#==========================================*
# I dati vengono letti dal file buffer     *
#------------------------------------------*
my $entity=$par_ser->parse(\*STDIN)       ; 

#==========================================*
# Individuazione elementi                  *
#------------------------------------------*
my $from=$entity->head->get('From')       ; 
my $subject=$entity->head->get('Subject') ; 
my @parts=$entity->parts                  ; 
my $aname='attachment001'                 ; 

#==========================================*
# Ciclo di scansione                       *
#------------------------------------------*
while(my $part = shift(@parts))
{ 
  if($part->parts)
  { 
      push @parts,$part->parts; # Nested multi-part 
      next; 
  } 
  my $type=$part->head->mime_type || $part->head->effective_type; 
  if($type !~ /^(text|message)/i)
  { # Not a text, save it 
      my $fil_nam=$part->head->recommended_filename || $aname; 
      $aname++; 
      my $io=$part->open("r"); 
      my $uniq=time().'-'.$$; 
        $fil_nam =~ s/[;<>\*\|`&\$!#\(\)\[\]\{\}:'"\n]//g; 
      open(F,">> $att_dir/$uniq-$fil_nam"); 
      my $buf; 
          while($io->read($buf,1024))
      { 
          print F $buf; 
      } 
      close(F); 
      $io->close; 
      open(LOG,">> $log_fil"); 

      print LOG localtime()." From: $from\tSubject: $subject\tFile: $uniq-$fil_nam\n"; 

      print LOG "Numero di messaggi: " . $num_msg . "\n\n";

      close(LOG); 
   } 
} 
#==========================================*
# Fine esecuzione script                   *
#------------------------------------------*
exit()                                    ;  



