#!/usr/bin/perl -w
#==========================================*
# Etichette SSCC 18 su PDF - formato A5    *
#                                          *
# Ad hoc NOBILI                            *
#                                          *
# ___ DA IMPLEMENTARE                      *
#                                          *
# ---------------------------------------- *
# Versione originale:   001 del 30/11/2023 *
#   Ultima revisione:   wip del 30/11/2023 *
# ---------------------------------------- *
#             Autore:   Nicola de Kunovich *
# ---------------------------------------- *
#                                          *
# Parametri in input : - file parametri    *
#                                          *
# ---------------------------------------- *
#                                          *
# Note : lo script prepara un file PDF     *
#        da inviare alla stampante         *
#        tratta con l'emulatore            *
#                                          *
# ---------------------------------------- *
#                                          *
# Standard SSCC 18:                        *
#                                          *
# - Cifra 1         : Estensione           *
# - Cifre da 2 a 10 : Assegnate da GS1     *
# - Cifre da 11 a 17: Progressivo numerico *
# - Cifra 18        : Check Digit          *
#                                          *
# (00)180800368987121660                   *
# - 1                                      *
# -  808003689                             *
# -           712166                       *
# -                 0                      *
#                                          *
# Standard UCC/EAN 128 (peso fisso):       *
#                                          *
# - (02) : GTIN Prodotto (EAN 14 chr ?)    *
# - (17) : YYMMDD data scadenza            *
# - (37) : Numero colli nel pallet         *
# - (10) : Numero lotto                    *
#                                          *
#==========================================*

# ESEMPI
# +C1 02 08003030210144 17 261231 37 00000052 §10 V25356375200
# (02)08003030210144(17)261231(37)00000052(10)V25356375200

      08003928031005
# (02)08003030210144 GTIN codice prodotto EAN13
# (17)261231         YYMMDD data scadenza
# (37)00000052       Numero colli nel pallet
# (10)V25356375200   Numero lotto



# (00)180800368987121660



# $num_doc = '(00)180800368987121660';


#==========================================*
# Moduli Perl                              *
#------------------------------------------*
use PDF::Reuse                            ;
use PDF::Reuse::Barcode                   ;
use strict;

#==========================================*
# Variabili in input                       *
#------------------------------------------*
my $num_prt = shift                       ;

#==========================================*
# Test su variabili in input               *
#------------------------------------------*
if (!$num_prt)
{ exit();}

#==========================================*
# Percorsi file                            *
#------------------------------------------*
my $pth_tmp = "/abd/spl/"                 ;
my $log_az1 = "/abd/asc/mod/elettra.pdf"  ;
my $log_az2 = "/abd/asc/mod/aeg.pdf"      ;
my $pth_csv = $pth_tmp . $num_prt . ".csv";
my $out_pdf = $pth_tmp . $num_prt . ".pdf";

#==========================================*
# Normalizzazioni                          *
#------------------------------------------*
my $cod_stp = ""                          ;
my $tip_eti = ""                          ;
my $num_eti = 0                           ;
my $pes_tot = 0                           ;
my $num_doc = ""                          ;
my $rag_cli = ""                          ;
my $via_cli = ""                          ;
my $loc_cli = ""                          ;
my $rag_vet = ""                          ;
my $via_vet = ""                          ;
my $loc_vet = ""                          ;
my $rif_doc = ""                          ;
my $str     = ""                          ;

#==========================================*
# Open file contenente i parametri         *
#------------------------------------------*
open (I_FILE, "$pth_csv") or die
     "Impossibile aprire il file '$pth_csv'";
my   @linea = <I_FILE>                    ;

#==========================================*
# Close del file                           *
#------------------------------------------*
close I_FILE                              ;

#==========================================*
# Ciclo di scansione per lettura parametri *
#------------------------------------------*
foreach my $row (@linea)
{
    #--------------------------------------*
    # Lettura linea                        *
    #--------------------------------------*
    my   @rec = split(/;/, $row)          ;
    #--------------------------------------*
    # Test su tipo record                  *
    #--------------------------------------*
    if  ($rec[0] eq "cod_stp")
    {
        #----------------------------------*
        # Codice stampante                 *
        #----------------------------------*
        $cod_stp = $rec[1]                ;
    }
     elsif ($rec[0] eq "tip_eti")
    {
        #----------------------------------*
        # Tipo etichetta                   *
        #----------------------------------*
        $tip_eti = $rec[1]                ;
    }
     elsif ($rec[0] eq "num_eti")
    {
        #----------------------------------*
        # Numero di etichette              *
        #----------------------------------*
        $num_eti = $rec[1]                ;
    }
     elsif ($rec[0] eq "pes_tot")
    {
        #----------------------------------*
        # Peso totale                      *
        #----------------------------------*
        $pes_tot = $rec[1]                ;
    }
     elsif ($rec[0] eq "num_doc")
    {
        #----------------------------------*
        # Numero documento                 *
        #----------------------------------*
        $num_doc = $rec[1]                ;
        $num_doc =~ s/\s+$//              ;

    }
     elsif ($rec[0] eq "rag_cli")
    {
        #----------------------------------*
        # Ragione sociale cliente          *
        #----------------------------------*
        $rag_cli = $rec[1]                ;
    }
     elsif ($rec[0] eq "via_cli")
    {
        #----------------------------------*
        # Indirizzo cliente                *
        #----------------------------------*
        $via_cli = $rec[1]                ;
    }
     elsif ($rec[0] eq "loc_cli")
    {
        #----------------------------------*
        # Localita' cliente                *
        #----------------------------------*
        $loc_cli = $rec[1]                ;
    }
     elsif ($rec[0] eq "rag_vet")
    {
        #----------------------------------*
        # Ragione sociale vettore          *
        #----------------------------------*
        $rag_vet = $rec[1]                ;
    }
     elsif ($rec[0] eq "via_vet")
    {
        #----------------------------------*
        # Indirizzo vettore                *
        #----------------------------------*
        $via_vet = $rec[1]                ;
    }
     elsif ($rec[0] eq "loc_vet")
    {
        #----------------------------------*
        # Localita' vettore                *
        #----------------------------------*
        $loc_vet = $rec[1]                ;
    }
     elsif ($rec[0] eq "rif_doc")
    {
        #----------------------------------*
        # Riferimento documento            *
        #----------------------------------*
        $rif_doc = $rec[1]                ;
    }
}

    #--------------------------------------*
    # DEBUG                                *
    #--------------------------------------*
#    print "Stampante : " . $cod_stp . "\n";
#    print "Tipo eti  : " . $tip_eti . "\n";
#    print "Num eti   : " . $num_eti . "\n";
#    print "Num DOC   : " . $num_doc . "\n";
#    print "Cliente   : " . $rag_cli . "\n";
#    print "   -      : " . $via_cli . "\n";
#    print "   -      : " . $loc_cli . "\n";

#==========================================*
# Deviazione in funzione del tipo di eti-  *
# chetta                                   *
#------------------------------------------*
if ($tip_eti == 1)
{
    &eti_001                              ;
}
 elsif ($tip_eti == 2)
{
    &eti_002                              ;
}
 else
{
    exit()                                ;
}

#------------------------------------------*
# Fine script                              *
#==========================================*

#==========================================*
# SUBROUTINES                              *
#==========================================*

#==========================================*
# Etichetta di tipo '1': segnacolli DDT    *
#------------------------------------------*
sub eti_001
{
    #======================================*
    # Ciclo di generazione e stampa per    *
    # ciascuna etichetta                   *
    #--------------------------------------*
    my $stp_ctr = 1                       ;
    while($stp_ctr <= $num_eti)
    {
        #----------------------------------*
        # Assegnazione nome file           *
        #----------------------------------*
        $out_pdf = $pth_tmp 
                 . $num_prt
                 . "."
                 . $stp_ctr
                 . ".pdf"                 ;
        #----------------------------------*
        # Inizializzazione file PDF        *
        #----------------------------------*
        prFile($out_pdf)                  ;
        #----------------------------------*
        # Impostazione pagina              *
        #----------------------------------*
        prMbox(0, 0, 285, 425)            ;
        #----------------------------------*
        # Font                             *
        #----------------------------------*
        prFont('Helvetica-Bold')          ;
        #----------------------------------*
        # Box pagina                       *
        #----------------------------------*
        prAdd("q 1 1 1 rg 10 10 270 400 re b Q");
        #----------------------------------*
        # Fincatura superiore              *
        #----------------------------------*
        prAdd("q 50 10 m 50 410 l S Q")   ; 
        #----------------------------------*
        # Fincatura centrale               *
        #----------------------------------*
        prAdd("q 190 10 m 190 410 l S Q") ; 
        #----------------------------------*
        # Fincatura verticale              *
        #----------------------------------*
        prAdd("q 190 140 m 240 140 l S Q") ; 
        #----------------------------------*
        # Fincatura inferiore              *
        #----------------------------------*
        prAdd("q 240 10 m 240 410 l S Q") ; 
        #----------------------------------*
        # Font per numero documento        *
        #----------------------------------*
        prFontSize(24)                    ;       
        #----------------------------------*
        # Numero documento                 *
        #                                  *
        #   Parametri di posizionamento    *
        #   ---------------------------    *
        # - Distanza dal bordo sinistro    *
        # - Distanza dal bordo inferiore   *
        # - Stringa da stampare            *
        # - Coefficiente di rotazione      *
        #----------------------------------*
        $str  = "DDT nr. "  
              . $num_doc                  ;
        prText(40, 150, $str,'','q3')     ;
        #----------------------------------*
        # Font per Ragione sociale         *
        #----------------------------------*
        prFontSize(28)                    ;       
        #----------------------------------*
        # Ragione sociale                  *
        #----------------------------------*
        &stp_str (90, 20, 'q3', $rag_cli) ;
        &stp_str (120, 20, 'q3', $via_cli);
        &stp_str (150, 20, 'q3', $loc_cli);
        #----------------------------------*
        # Font per Numero colli            *
        #----------------------------------*
        prFontSize(26)                    ;       
        #----------------------------------*
        # Numero colli                     *
        #----------------------------------*
        $str  = "Colli "
              . $stp_ctr
              . " di "
              . $num_eti                  ;
        prText(230, 200, $str,'','q3')    ;
        
        #----------------------------------*
        # Prompt per Vettore               *
        #----------------------------------*
        $rag_vet =~ s/\s+$//              ;
        if (length($rag_vet) != 0)
        {
        prFontSize(12)                    ;       
        $str  = "Vettore"                 ;
        prText(253, 22, $str,'','q3')     ;
        }
        #----------------------------------*
        # Font per Vettore                 *
        #----------------------------------*
        prFontSize(18)                    ;       
        #----------------------------------*
        # Ragione sociale Vettore          *
        #----------------------------------*
        $str  = $rag_vet                  ;
        prText(273, 20, $str,'','q3')     ;
        #----------------------------------*
        # Logo Elettra                     *
        #----------------------------------*
        prImage(  { file    => $log_az1,
                    page    => 1,
                    imageNo => 1,
                    x       => 20,
                    y       => 20,
                    rotate  => 'q3',
                    size    => 0.2 }  )   ;
        #----------------------------------*
        # Logo AEG                         *
        #----------------------------------*
        prImage(  { file    => $log_az2,
                    page    => 1,
                    imageNo => 1,
                    x       => 20,
                    y       => 340,
                    rotate  => 'q3',
                    size    => 0.5 }  )   ;
        #----------------------------------*
        # Barcode per Numero documento     *
        #----------------------------------*
        PDF::Reuse::Barcode::Code128(x      => 235,
                                     y      => 30,
                                     value  => $num_doc,
                                     rotate => 90);
        #----------------------------------*
        # Chiusura PDF                     *
        #----------------------------------*
        prEnd()                           ;
        #----------------------------------*
        # Stampa file PDF                  *
        #----------------------------------*
        system("cat $out_pdf | lpr -P$cod_stp");
        #----------------------------------*
        # Incremento contatore             *
        #----------------------------------*
        $stp_ctr++                        ;
    }
}

#==========================================*
# Etichetta di tipo '2': Riferimenti ODS   *
#------------------------------------------*
sub eti_002
{
    #======================================*
    # Ciclo di generazione e stampa per    *
    # ciascuna etichetta                   *
    #--------------------------------------*
    my $stp_ctr = 1                       ;
    while($stp_ctr <= $num_eti)
    {
        #----------------------------------*
        # Assegnazione nome file           *
        #----------------------------------*
        $out_pdf = $pth_tmp 
                 . $num_prt
                 . "."
                 . $stp_ctr
                 . ".pdf"                 ;
        #----------------------------------*
        # Inizializzazione file PDF        *
        #----------------------------------*
        prFile($out_pdf)                  ;
        #----------------------------------*
        # Impostazione pagina              *
        #----------------------------------*
        prMbox(0, 0, 285, 285)            ;
        #----------------------------------*
        # Font                             *
        #----------------------------------*
        prFont('Helvetica-Bold')          ;
        #----------------------------------*
        # Box pagina                       *
        #----------------------------------*
        prAdd("q 1 1 1 rg 10 10 270 270 re b Q"); 
        #----------------------------------*
        # Fincatura superiore              *
        #----------------------------------*
        prAdd("q 50 10 m 50 280 l S Q")   ; 
        #----------------------------------*
        # Fincatura inferiore              *
        #----------------------------------*
        prAdd("q 220 10 m 220 280 l S Q") ; 
        #----------------------------------*
        # Font per numero documento        *
        #----------------------------------*
        prFontSize(20)                    ;       
        #----------------------------------*
        # Numero documento                 *
        #                                  *
        #   Parametri di posizionamento    *
        #   ---------------------------    *
        # - Distanza dal bordo sinistro    *
        # - Distanza dal bordo inferiore   *
        # - Stringa da stampare            *
        # - Coefficiente di rotazione      *
        #----------------------------------*
        $str  = "ODS : "  
              . $num_doc                  ;
        prText(40, 140, $str,'','q3')     ;
        #----------------------------------*
        # Font per Ragione sociale         *
        #----------------------------------*
        prFontSize(30)                    ;       
        #----------------------------------*
        # Ragione sociale                  *
        #----------------------------------*
        &stp_str (90, 20, 'q3', $rag_cli) ;
        prFontSize(16)                    ;       
        prText(130, 20, $via_cli,'','q3') ;
        prText(170, 20, $loc_cli,'','q3') ;
        #----------------------------------*
        # Riferimento                      *
        #----------------------------------*
        &stp_rif (258, 20, 'q3', $rif_doc) ;
        #----------------------------------*
        # Logo Elettra                     *
        #----------------------------------*
        prImage(  { file    => $log_az1,
                    page    => 1,
                    imageNo => 1,
                    x       => 20,
                    y       => 20,
                    rotate  => 'q3',
                    size    => 0.2 }  )   ;
        #----------------------------------*
        # Chiusura PDF                     *
        #----------------------------------*
        prEnd()                           ;
        #----------------------------------*
        # Stampa file PDF                  *
        #----------------------------------*
        system("cat $out_pdf | lpr -P$cod_stp");
        #----------------------------------*
        # Incremento contatore             *
        #----------------------------------*
        $stp_ctr++                        ;
    }
}

#==========================================*
# Stampa stringa con eventuale ritaratura  *
# del font size                            *
#------------------------------------------*
sub stp_str
{
    #======================================*
    # Variabili in input                   *
    #--------------------------------------*
    my $xxx = shift                       ;
    my $yyy = shift                       ;
    my $rot = shift                       ;
    my $str = shift                       ;
    #--------------------------------------*
    # Pulizia spazi vuoti a fine stringa   *
    #--------------------------------------*
    $str =~ s/\s+$//                      ;
    #--------------------------------------*
    # Determinazione lunghezza stringa     *
    #--------------------------------------*
    my $lun = length($str)                ;
    #--------------------------------------*
    # Eventuale ritaratura FontSize        *
    #--------------------------------------*
    if ($lun >= 10)
    {
        prFontSize(20)                    ;       
    }
     else
    {
        prFontSize(30)                    ;       
    }
    #--------------------------------------*
    # Emissione stringa                    *
    #--------------------------------------*
    prText($xxx, $yyy, $str, '', $rot)    ;
}

#==========================================*
# Stampa stringa con eventuale ritaratura  *
# del font size - Riferimento              *
#------------------------------------------*
sub stp_rif
{
    #======================================*
    # Variabili in input                   *
    #--------------------------------------*
    my $xxx = shift                       ;
    my $yyy = shift                       ;
    my $rot = shift                       ;
    my $str = shift                       ;
    #--------------------------------------*
    # Pulizia spazi vuoti a fine stringa   *
    #--------------------------------------*
    $str =~ s/\s+$//                      ;
    #--------------------------------------*
    # Determinazione lunghezza stringa     *
    #--------------------------------------*
    my $lun = length($str)                ;
    #--------------------------------------*
    # Eventuale ritaratura FontSize        *
    #--------------------------------------*
    if ($lun >= 13)
    {
        prFontSize(28)                    ;       
    }
     else
    {
        prFontSize(36)                    ;       
    }
    #--------------------------------------*
    # Emissione stringa                    *
    #--------------------------------------*
    prText($xxx, $yyy, $str, '', $rot)    ;
}
