#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per backup PERONTECNICI su   *
# Server interno                           *
#                                          *
# t_ptu_backup                             *
#                                          *
# ---------------------------------------- *
# Versione originale:  001 del 29/05/2018  *
#   Ultima revisione:  NdK del 30/05/2018  *
# ---------------------------------------- *
#             Autore:  Nicola de Kunovich  *
# ---------------------------------------- *
#                                          *
# In crontab                               *
#                                          *
#==============================#           *
# Backup su server interno     # alle 22:30*
#==============================#           *
#30 22 * * *	/abd/etc/t_ptu_backup        *
#     1>/abd/asc/log/t_ptu_backup_ok.log   *
#     2>/abd/asc/log/t_ptu_backup_KO.log   *
#==========================================*

#==========================================*
# Moduli Perl di base                      *
#------------------------------------------*
use Net::FTP                              ;

#==========================================*
# Variabili di configurazione              *
#------------------------------------------*
my $ftps = '192.168.1.150'                ;
my $ftpu = 'tangram'                      ;
my $ftpp = 'Passw0rd18'                   ;
my $ftpd = '/tangram'                     ;
my $fput = '/tmp/TANGRAM_BACKUP.gz'       ;
my $fazi = '/tmp/PTU_BACKUP.gz'           ;

#==========================================*
# Preparazione dei backup                  *
#------------------------------------------*
system("tar cvfz " . $fput . " /abd")     ;
system("tar cvfz " . $fazi . " /abd/azi") ;

#==========================================*
# Sub-routine di trasferimento file        *
#------------------------------------------*
my $link = &ftpf                          ;

#==========================================*
# SUB-ROUTINES                             *
#==========================================*

#==========================================*
# Subroutine di trasferimento del file     *
#------------------------------------------*
sub ftpf
{
    #--------------------------------------*
    # Comodo per errori                    *
    #--------------------------------------*
    my $erra=0                            ;

    #--------------------------------------*
    # Apertura connessione                 *
    #--------------------------------------*
    $ftp = Net::FTP->new($ftps,
                         Debug => 0)
           or die "Non connesso a: $@"    ;

    #--------------------------------------*
    # Login connessione                    *
    #--------------------------------------*
    $ftp->login($ftpu,$ftpp)
          or die "Login errato ",
                 $ftp->message            ;
    
    #--------------------------------------*
    # Posizionamento cartella destinazione *
    #--------------------------------------*
    $ftp->cwd($ftpd) or $erra=1           ;
                 
    #--------------------------------------*
    # Modalita' Binary                     *
    #--------------------------------------*
    $ftp->binary
          or die "Binary NO",
                 $ftp->message            ;

    #--------------------------------------*
    # Trasferimento backup generale        *
    #--------------------------------------*
    $ftp->put($fput)
          or die "put1 fallita ",
                 $ftp->message            ;

    #--------------------------------------*
    # Trasferimento backup 'ptu'           *
    #--------------------------------------*
    $ftp->put($fazi)
          or die "put2 fallita ",
                 $ftp->message            ;

    #--------------------------------------*
    # Chiusura FTP                         *
    #--------------------------------------*
    $ftp->quit                            ;
}

