#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per pulire aree XML di ELE   *
#==========================================*

my $com1 = 'mysql -u root -ploppio2 -D ele -e "truncate table xml_for"';
my $com2 = 'mysql -u root -ploppio2 -D ele -e "truncate table xml_frr"';

system("rm /abd/azi/ele/xft")             ;
system("rm /abd/azi/ele/xfr")             ;
system("rm /abd/azi/ele/xfx")             ;

system("rm -rf  /abd/asc/ele/att/2021/*")      ;

system("rm -rf /abd/asc/ele/htm/2020/*")      ;
system("rm -rf  /abd/asc/ele/htm/2021/*")      ;

system("rm -rf  /abd/tmp/*.txt")      ;
system("rm -rf  /abd/tmp/*.xml")      ;

system("mv /abd/asc/ele/scf/2021/*.p7m /abd/asc/ele/scf")      ;
system("mv /abd/asc/ele/scf/2021/*.xml /abd/asc/ele/scf")      ;
system("mv /abd/asc/ele/scf/2020/*.xml /abd/asc/ele/scf")      ;

system($com1)      ;
system($com2)      ;

