#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per creazione cartella in    *
# cartella PDF utente                      *
#                                          *
# t_scf_pdf_mkd                            *
#                                          *
# ---------------------------------------- *
# Versione originale:  001 del 06/02/18    *
#   Ultima revisione:  NdK del 06/02/18    *
# ---------------------------------------- *
#             Autore:  Nicola de Kunovich  *
# ---------------------------------------- *
#                                          *
# In input : - utente                      *
#            - nome cartella               *
#                                          *
# ---------------------------------------- *
#                                          *
# N.B.: chiamato dal programma 'pscf300j'  *
#                                          *
# ___ FUNZIONA MA MAI UTILIZZATO !!! ___   *
#                                          *
#------------------------------------------*

#==========================================*
# Variabili lette in input                 *
#------------------------------------------*
my $uten = shift                          ;
my $fldr = shift                          ;

#==========================================*
# Variabili di comodo                      *
#------------------------------------------*
my $patb = "/abd/asc/"                    ;
my $cmnd = "mkdir "
         . $patb
         . $uten
         . "/pdf/out/"
         . $fldr                          ;

#==========================================*
# Esecuzione comando creazione directory   *
#------------------------------------------*
system($cmnd)                             ;

#==========================================*
# Esecuzione comando per privilegi         *
#------------------------------------------*
system("chmod 0777 "
       . $patb
       . $uten
       . "/pdf/out/"
       . $fldr)                           ;

