#!/usr/bin/perl -w
#==========================================*
# Modulo Perl di invio posta con autenti-  *
# cazione Base64 o MD5 o SHA1              *
#                                          *
# t_sender_aut                             *
#                                          *
# Invio di messaggi ad una lista di        *
# indirizzi e con i relativi allegati PDF  *
# (utilizzato per i lotti di fatture PDF)  *
#                                          *
# ___ NON UTILIZZATO: DA FINIRE ___        *
#                                          *
# ---------------------------------------- *
# Versione originale:   001 del 31/10/12   *
#   Ultima revisione:   NdK del 03/12/15   *
# ---------------------------------------- *
#             Autore:   Nicola de Kunovich *
# ---------------------------------------- *
#                                          *
# In input : - codice azienda              *
#            - server SMTP                 *
#            - mittente                    *
#            - username                    *
#            - password                    *
#            - indirizzi (opzionale)       *
#            - soggetto  (opzionale)       *
#            - messaggio (opzionale)       *
#                                          *
# ---------------------------------------- *
# N.B.: i campi in input sono separati da  *
#       virgola ','                        *
#                                          *
# ---------------------------------------- *
# N.B.: UNIFORMABILE CON 't_sender_ssl'    *
# ---------------------------------------- *
# N.B.: il campo indirizzi puo' contenere  *
#       il nome di un file di indirizzi e  *
#       percorsi di allegati, oppure un    *
#       solo indirizzo e un solo allegato  *
#       separati da '#'                    *
#------------------------------------------*

#==========================================*
# Moduli Perl utilizzati                   *
#------------------------------------------*
use Net::SMTP_auth                        ;
use MIME::Base64                          ;
use MIME::Lite                            ;
use File::Spec                            ;
use File::Basename                        ;
use LWP::MediaTypes                       ;

#==========================================*
# Variabili statiche                       *
#------------------------------------------*
my $base = '/abd/asc/'                    ;
my $temp = '/tmp/'                        ;
#
my $sogg = 'sogg.txt'                     ;
my $mess = 'mess.txt'                     ;
my $emla = 'indi.txt'                     ;
#
my $wsog = ''                             ;
my $wmes = ''                             ;
my $wind = ''                             ;

#==========================================*
# Variabili lette in input                 *
#------------------------------------------*
#    *-------------------------------------*
#    * Lettura variabile in input          *
#    *-------------------------------------*
$inpt = $ARGV[0]                          ;

#==========================================*
# Help                                     *
#------------------------------------------*
if (!$ARGV[0] || $ARGV[0] eq "-help")
{
    print "\n"
        . "Uso : (parametri "
        . "separati da virgola)"
        . "\n"
        . "> t_sender_aut"
        . "\n"
        . "           AZIENDA(default: doc),"
        . "\n"
        . "           SERVER_SMTP,"
        . "\n"
        . "           MITTENTE,"
        . "\n"
        . "           USERID_SSL,"
        . "\n"
        . "           PASSWORD_SSL,"
        . "\n"
        . "           INDIRIZZI(opz),"
        . "\n"
        . "           SOGGETTO(opz),"
        . "\n"
        . "           MESSAGGIO(opz),"
        . "\n"
        . "\n"
        . "Release : 03/04/2013"
        . "\n"
        . "\n"
        . "(C) Copyright - dKb"
        . "\n"
        . "\n"                            ;
    exit()                                ;
}

#    *-------------------------------------*
#    * Separazione dei componenti (,)      *
#    *-------------------------------------*
@vars = split(/,/, $inpt)                 ;
#    *-------------------------------------*
#    * Azienda Tangram                     *
#    *-------------------------------------*
my $atgm = $vars[0]                       ;
#    *-------------------------------------*
#    * Server SMTP                         *
#    *-------------------------------------*
my $srvr = $vars[1]                       ;
#    *-------------------------------------*
#    * Mittente                            *
#    *-------------------------------------*
my $mitt = $vars[2]                       ;
#    *-------------------------------------*
#    * Username autenticazione             *
#    *-------------------------------------*
my $user = $vars[3]                       ;
#    *-------------------------------------*
#    * Password autenticazione             *
#    *-------------------------------------*
my $pass = $vars[4]                       ;
#    *-------------------------------------*
#    * Indirizzi                          *
#    *-------------------------------------*
my $indi = $vars[5]                       ;
#    *-------------------------------------*
#    * Soggetto                            *
#    *-------------------------------------*
my $sogi = $vars[6]                       ;
#    *-------------------------------------*
#    * Messaggio                           *
#    *-------------------------------------*
my $mesi = $vars[7]                       ;

#==========================================*
# Debug (da scommentare)                   *
#------------------------------------------*
#    print "azienda :" . $vars[0] . "\n";
#    print $vars[1] . "\n";
#    print $vars[2] . "\n";
#    print $vars[3] . "\n";
#    print $vars[4] . "\n";
#    print $vars[5] . "\n";
#    print $vars[6] . "\n";
#    print $vars[7] . "\n";
#    exit ();

#==========================================*
# Sub-routine per lettura soggetto         *
#------------------------------------------*
&soggetto                                 ;

#==========================================*
# Sub-routine per lettura testo            *
#------------------------------------------*
&messaggio                                ;

#=========================================*
# Sub-routine di spedizione               *
#-----------------------------------------*
&spedisci                                 ;

#==========================================*
# SUB-ROUTINES                             *
#==========================================*

#=========================================*
# Spedizione                              *
#-----------------------------------------*
sub spedisci 
{
    #-------------------------------------*
    # Se passata una lista                *
    #-------------------------------------*
    if ($indi !~ /\@/)
    {
        &lista                            ;
    }
    #-------------------------------------*
    # Se passato un singolo indirizzo     *
    #-------------------------------------*
    else 
    {
        @elem = split(/#/, $indi)         ;
        &send                             ;
    };
}

#==========================================*
# Apertura file contenente il soggetto     *
#------------------------------------------*
sub soggetto
{
    #--------------------------------------*
    # Verifica variabile letta             *
    #--------------------------------------*
    if (!$sogi)
    {
        $wsog = $sogg                     ;
    } else
    {
        $wsog = $sogi                     ;
    }
    
    #--------------------------------------*
    # Test se si tratta di un nome file    *
    #--------------------------------------*
    if ($wsog =~ /.txt/)
    {
        #----------------------------------*
        # Composizione directory           *
        #----------------------------------*
        my $wdir = $base
                 . $atgm
                 . $temp
                 . $wsog                  ;
        #----------------------------------*
        # Open                             *
        #----------------------------------*
        open (SOGGETTO, "$wdir")or die
         "Impossibile aprire file '$wdir'";
        @subject=<SOGGETTO>               ;
        #----------------------------------*
        # Close                            *
        #----------------------------------*
        close SOGGETTO                    ;
    } else
    {
        @subject = split(/_/, $wsog )     ;
    }
}

#==========================================*
# Apertura file contenente il messaggio    *
#------------------------------------------*
sub messaggio
{
    #--------------------------------------*
    # Verifica variabile letta             *
    #--------------------------------------*
    if (!$mesi)
    {
        $wmes = $mess                     ;
    } else
    {
        $wmes = $mesi                     ;
    }
    #--------------------------------------*
    # Composizione directory               *
    #--------------------------------------*
    my $wdir = $base
             . $atgm
             . $temp
             . $wmes                      ;
    #--------------------------------------*
    # Open                                 *
    #--------------------------------------*
    open (MESSAGE, "$wdir")
          or die
         "Impossibile aprire file '$mess'";
    @message=<MESSAGE>                    ;
    #--------------------------------------*
    # Close                                *
    #--------------------------------------*
    close MESSAGE                         ;
    #--------------------------------------*
    # Compattazione testo letto            *
    #--------------------------------------*
    $testo = qq{@message}                 ;
}

#==========================================*
# Invio ad una lista                       *
#------------------------------------------*
sub lista
{
    #--------------------------------------*
    # Verifica variabile letta             *
    #--------------------------------------*
    if (!$indi)
    {
        $wind = $emla                     ;
    } else
    {
        $wind = $indi                     ;
    }
    #--------------------------------------*
    # Composizione directory               *
    #--------------------------------------*
    my $wdir = $base
             . $atgm
             . $temp
             . $wind                      ;
    #--------------------------------------*
    # Open                                 *
    #--------------------------------------*
    open (INDIRIZZI, "$wdir")or die
        "Impossibile aprire file indirizzi";
    @indirizzo = <INDIRIZZI>              ;
    #--------------------------------------*
    # Ciclo di scansione file              *
    #--------------------------------------*
    foreach $indirizzo (@indirizzo)
    {
        @elem = split(/,/, $indirizzo)    ;
        if ($elem[0] !~ /\@/)
            {next}
            else {&send}                  ;
    }

    #--------------------------------------*
    # Close                                *
    #--------------------------------------*
    close (INDIRIZZI)                     ;
}

#==========================================*
# Singolo invio                            *
#------------------------------------------*
sub send
{

    #--------------------------------------*
    # Estrazione nome allegato senza       *
    # estensione                           *
    #--------------------------------------*
   (my $fnams,
    my $direc,
    my $exten) = fileparse($elem[1],'\..*');
    #--------------------------------------*
    # Composizione soggetto e allegato     *
    # eliminando blank superflui dal sog-  *
    # getto del file                       *
    #--------------------------------------*
    my $oggw = qq{@subject}               ;
    $oggw =~ s/^\s+//                     ;
    $oggw =~ s/\s+$//                     ;    
    my $ogge = $oggw . " - " . $fnams     ;

    #-------------------------------------*
    # Invio vero e proprio                *
    #-------------------------------------*
      $msg = MIME::Lite->new
    (
        #---------------------------------*
        # Mittente                        *
        #---------------------------------*
        From    =>$mitt,
        #---------------------------------*
        # Destinatario e mittente         *
        #---------------------------------*
        To      =>$elem[0],
        
        
        #---------------------------------*
        # Copia per il mittente: sempre   *
        #                                 *
        # N.B.: non va in MIME::Lite!     *
        #---------------------------------*
        Bcc     =>$mitt,
        #---------------------------------*
        # Oggetto                         *
        #---------------------------------*
        Subject =>$ogge,
        #---------------------------------*
        # Tipo messaggio                  *
        #---------------------------------*
        Type    =>'multipart/mixed',
    );
    

    $msg->attach
    (
        Type    => 'text/html',
        Data    => $testo
    );

    #--------------------------------------*
    # Estrazione nome allegato             *
    #--------------------------------------*
    my $fname = basename($elem[1])        ;
    #-------------------------------------*
    # Eventuale attachement               *
    #-------------------------------------*
    if ($fname)
        {
            $msg->attach
                (Type        => 'application/pdf',
                 Path        => $elem[1],
                 Filename    => $fname,
                 Disposition => 'attachment'
                );
        }

    #--------------------------------------*
    # Invio vero e proprio                 *
    #--------------------------------------*
    my $smtp = Net::SMTP_auth -> new($srvr, debug=>1);

    #--------------------------------------*
    # Autenticazione                       *
    #--------------------------------------*
        $smtp -> auth( 'LOGIN', $user, $pass);

    #--------------------------------------*
    # Preparazione messaggio               *
    #--------------------------------------*
        $smtp->mail($mitt)                ;
        $smtp->to($elem[0])             ;
        $smtp -> data()                   ;
        
        $smtp -> datasend( $msg->as_string());
        $smtp -> dataend()                ;
        $smtp -> quit                     ;
    
}

