#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per salvataggio provvisorio  *
# backup di SIRI su Server WEB             *
#                                          *
# t_sir_backup                             *
#                                          *
# ---------------------------------------- *
# Versione originale:  001 del 20/02/2013  *
#   Ultima revisione:  NdK del 20/02/2013  *
# ---------------------------------------- *
#             Autore:  Nicola de Kunovich  *
# ---------------------------------------- *
#                                          *
# In crontab, dopo la copia                *
#                                          *
# [NON ATTIVO] dal 30/03/18                *
#                                          *
#==========================================*

#==========================================*
# Moduli Perl di base                      *
#------------------------------------------*
use Net::FTP                              ;

#==========================================*
# Variabili di configurazione              *
#------------------------------------------*
my $ftps = '10.254.254.194'               ;
my $ftpu = 'master'                       ;
my $ftpp = 'alter1'                       ;
my $ftpd = '/abd/SAV/'                    ;
my $fput = '/tmp/SAV_ABD.TAR'             ;

#==========================================*
# Sub-routine di trasferimento file        *
#------------------------------------------*
my $link = &ftpf                          ;

#==========================================*
# SUB-ROUTINES                             *
#==========================================*

#==========================================*
# Subroutine di trasferimento del file     *
#------------------------------------------*
sub ftpf
{
    #--------------------------------------*
    # Comodo per errori                    *
    #--------------------------------------*
    my $erra=0                            ;

    #--------------------------------------*
    # Apertura connessione                 *
    #--------------------------------------*
    $ftp = Net::FTP->new($ftps,
                         Debug => 0)
           or die "Non connesso a: $@"    ;

    #--------------------------------------*
    # Login connessione                    *
    #--------------------------------------*
    $ftp->login($ftpu,$ftpp)
          or die "Login errato ",
                 $ftp->message            ;
    
    #--------------------------------------*
    # Posizionamento cartella destinazione *
    #--------------------------------------*
    $ftp->cwd($ftpd) or $erra=1           ;
                 
    #--------------------------------------*
    # Modalita' Binary                     *
    #--------------------------------------*
    $ftp->binary
          or die "Binary NO",
                 $ftp->message            ;

    #--------------------------------------*
    # Trasferimento                        *
    #--------------------------------------*
    $ftp->put($fput)
          or die "put fallita ",
                 $ftp->message            ;

    #--------------------------------------*
    # Chiusura FTP                         *
    #--------------------------------------*
    $ftp->quit                            ;
}

