#!/usr/bin/perl -w
#==========================================*
# Modulo Perl per creare un file tempora-  *
# neo, chiamato da 'pscf3710', con la lis- *
# ta dei documenti 'xml' ricevuti dai      *
# fornitori                                *
#                                          *
# t_xml_scf_dir                            *
#                                          *
# N.B.: Utilizzato da 'pscf3701'           *
#                                          *
# ___ DA SISTEMARE - MANCA ANNO            *
#                                          *
# ---------------------------------------- *
# Versione originale:   001 del 13/01/19   *
#   Ultima revisione:   wip del 17/01/19   *
# ---------------------------------------- *
#             Autore:   Nicola de Kunovich *
# ---------------------------------------- *
#                                          *
# In input : - codice utente               *
#                                          *
#            - codice azienda              *
#                                          *
#            - data iniziale (opzionale)   *
#                                          *
#            - data finale (opzionale)     *
#                                          *
#            - partita iva fornitore       *
#              (opzionale)                 *
#                                          *
#==========================================*

#==========================================*
# Moduli Perl utilizzati                   *
#------------------------------------------*
use IO::File                              ;
use File::Copy                            ;
use File::Basename                        ;
use XML::Simple                           ;
use Date::Manip                           ;
use utf8                                  ;
use Unicode::Normalize                    ;
use strict                                ;
use warnings                              ;

#==========================================*
# Valori in input                          *
#------------------------------------------*
my $cod_usr = shift                       ;
my $cod_azi = shift                       ;
my $dat_min = shift                       ;
my $dat_max = shift                       ;
my $piv_fnt = shift                       ;

#==========================================*
# Test su valori in input                  *
#------------------------------------------*
#------------------------------------------*
# Codice azienda e codice utente           *
#------------------------------------------*
if (!$cod_azi || !$cod_usr){exit()}       ;
#------------------------------------------*
# Data minima                              *
#------------------------------------------*
if (!$dat_min || $dat_min == 0)
{
    $dat_min='2000-01-01'                 ;
} else
{
    $dat_min = &dat_inp ($dat_min)        ;
}
#------------------------------------------*
# Data massima                             *
#------------------------------------------*
if (!$dat_max || $dat_max == 9999999)
{
    $dat_max='2200-12-31'                 ;
} else
{
    $dat_max = &dat_inp ($dat_max)        ;
}

#------------------------------------------*
# Partita Iva                              *
#------------------------------------------*
if (!$piv_fnt || $piv_fnt == 00000000000)
    {$piv_fnt=''}                         ;

#==========================================*
# Variabili definite                       *
#------------------------------------------*
#------------------------------------------*
# Directory di lavoro                      *
#------------------------------------------*
my $cfg_bas = "/abd/asc/cfg/t_xml_scf_dir.ini";
my %cnf_ele = do $cfg_bas                 ;
my $pth_scf = $cnf_ele{pth_scf}           ;
my $pth_tmp = $cnf_ele{pth_tmp}           ;

my $dir_xml = "/abd/asc/"
            . $cod_azi
            . "/"
            . $pth_scf
            . "/"                    ;
            
#==========================================*
# DEBUG                                    *
#------------------------------------------*
print "dir_xml = " . $dir_xml . "\n"    ;
exit()                                  ;
            
#------------------------------------------*
# File temporaneo contenente la lista      *
#------------------------------------------*
my $lst_tmp = $pth_tmp
            . $cod_azi
            . "_"
            . $cod_usr
            . "_pscf3710.tmp"            ;
        
#==========================================*
# Ciclo di scansione cartella              *
#------------------------------------------*
opendir(DIR, $dir_xml)                    ;
my @dir=grep { !/^\.+$/ } sort readdir(DIR)    ;
closedir(DIR)                             ;

#=========================================*
# Open del file di output                 *
#-----------------------------------------*
open (OUTFILE, ">$lst_tmp") or die
         "Impossibile aprire il file"     ;

#==========================================*
# Scansione elenco dei file                *
#------------------------------------------*
foreach my $fil_dir (@dir)
{
    #--------------------------------------*
    # Skip directory                       *
    #--------------------------------------*
    if(-d $fil_dir)
    { next;}                              ;
    #--------------------------------------*
    # Skip dei file "."                    *
    #--------------------------------------*
    if($fil_dir eq "." || $fil_dir eq "..")
    { next;}                              ;
    #--------------------------------------*
    # Skip dei file che iniziano  "._"     *
    #--------------------------------------*
    my $prffil = substr($fil_dir,0,2)     ;
    if($prffil eq "._")
    { next;}                              ;
    #--------------------------------------*
    # Test che non sia una directory il    *
    # file trattato                        *
    #--------------------------------------*
    if (! -d $fil_dir)
    {
        #----------------------------------*
        # Creazione path completo          *
        #----------------------------------*
        my $fil_pth = $dir_xml . $fil_dir ;
        my $new_pth = $pth_tmp . $fil_dir ;
        #----------------------------------*
        # Copia del file nella cartella    *
        # dei file temporanei              *
        #----------------------------------*

    if (! -d $fil_pth)
        {
	 copy($fil_pth, $new_pth) or die
	     "Copia del file $fil_pth fallita: $!"  ;
	     }
	     
        #----------------------------------*
        # Estrazione nome file             *
        #----------------------------------*
       (my $fil_nam,
        my $fil_pat,
        my $fil_ext) = fileparse($fil_dir, qr/\.[^.]*/);
        #----------------------------------*
        # Skip dei file NON '.xml' o 'p7m' *
        #----------------------------------*
        if ($fil_ext ne ".xml" && $fil_ext ne ".p7m")
        { next;}                          ;
        #----------------------------------*
        # Eventuale estrazione preliminare *
        # se estensione 'p7m'              *
        #----------------------------------*
        if ($fil_ext eq ".p7m")
        {
            #------------------------------*
            # Nuovo path                   *
            #------------------------------*
            my $new_xml = $pth_tmp . $fil_nam;
            #------------------------------*
            # Comando di estrazione        *
            #------------------------------*
            my $sys_cmd = "openssl smime -verify "
                . "-noverify -in $new_pth "
                . "-inform DER -out "
                . $new_xml                ;
            #------------------------------*
            # Esecuzione                   *
            #------------------------------*
            system($sys_cmd . "  >/dev/null 2>&1");
            #------------------------------*
            # Assegnazione nome file       *
            #------------------------------*
            $fil_pth = $new_xml           ;
           # $fil_dir = $fil_nam           ;
        }
        #----------------------------------*
        # Lettura dati singolo file        *
        #----------------------------------*
        my @rea_dat = &rea_doc($fil_pth)  ;
        #----------------------------------*
        # Partita Iva                      *
        #----------------------------------*
        my $rea_piv = $rea_dat[0]         ;
        #----------------------------------*
        # Data documento                   *
        #----------------------------------*
        my $rea_ddc = $rea_dat[1]         ;
        #----------------------------------*
        # Numero documento                 *
        #----------------------------------*
        my $rea_ndc = $rea_dat[2]         ;
        #----------------------------------*
        # Ragione sociale                  *
        #----------------------------------*
        my $rea_rag = $rea_dat[3]         ;
           $rea_rag =~ s/^\s+|\s+$//g     ;
        #----------------------------------*
        # Test su partita Iva              *
        #----------------------------------*
        if ($piv_fnt ne '' && $piv_fnt ne $rea_piv)
        {
            next                          ;
        }
        #----------------------------------*
        # Test su data minima              *
        #----------------------------------*
        my $cnf_dmi = &dat_cnf($rea_ddc,$dat_min);
        if ($cnf_dmi <0)
        {
            next                          ;
        }
        #----------------------------------*
        # Test su data massima             *
        #----------------------------------*
        my $cnf_dma = &dat_cnf($rea_ddc,$dat_max);
        if ($cnf_dma >0)
        {
            next                          ;
        }
        #----------------------------------*
        # Formattazione valori letti per   *
        # l'output                         *
        #----------------------------------*
        my $dat_fmt = &dat_out($rea_ddc)  ;
        
        my $lin_fmt = sprintf("%-20s%-10s%-16s%-35s%-40s\n",
                              $rea_ndc,
                              $dat_fmt,
                              $rea_piv,
                              $fil_dir,
                              $rea_rag)   ;
        #----------------------------------*
        # Scrittura su file di output      *
        #----------------------------------*
        print OUTFILE $lin_fmt            ;
    }
}

#=========================================*
# Close file di output                    *
#-----------------------------------------*
close (OUTFILE)                           ;

#==========================================*
# SUBROUTINES                              *
#==========================================*

#==========================================*
# Determinazione dati dal documento        *
#------------------------------------------*
sub rea_doc 
{
    #--------------------------------------*
    # File in input                        *
    #--------------------------------------*
    my $pthfil = shift                    ;
    #--------------------------------------*
    # Caricamento file                     *
    #--------------------------------------*
    my $xml = XML::Simple->new()          ;
    my $data = XMLin($pthfil)             ;
    #--------------------------------------*
    # Partita Iva cedente                  *
    #--------------------------------------*
    my $pmt_doc = $data->{FatturaElettronicaHeader}
                       ->{CedentePrestatore}
                       ->{DatiAnagrafici}
                       ->{IdFiscaleIVA}   ;
    my $prt_iva = $pmt_doc->{IdCodice}    ;
    #--------------------------------------*
    # Ragione sociale cedente              *
    #--------------------------------------*
       $pmt_doc = $data->{FatturaElettronicaHeader}
                       ->{CedentePrestatore}
                       ->{DatiAnagrafici}
                       ->{Anagrafica}     ;
    my $rag_soc = $pmt_doc->{Denominazione};
    #
    if($rag_soc)
    {
        my $rag_wrk = NFKD($rag_soc)      ;
           $rag_wrk =~ s/\p{NonspacingMark}//g;
           $rag_soc = $rag_wrk            ;
    }
     else
    {
           $rag_soc = "???"               ;
    }
    #--------------------------------------*
    # Cognome cedente (se persona fisica)  *
    #--------------------------------------*
       $pmt_doc = $data->{FatturaElettronicaHeader}
                       ->{CedentePrestatore}
                       ->{DatiAnagrafici}
                       ->{Anagrafica}     ;
    my $cog_nom = $pmt_doc->{Cognome}     ;
    #
    if($cog_nom)
    {
        my $cog_wrk = NFKD($cog_nom)      ;
           $cog_wrk =~ s/\p{NonspacingMark}//g;
           $cog_nom = $cog_wrk            ;
    }
     else
    {
           $cog_nom = "???"               ;
    }
    #--------------------------------------*
    # Utilizzare o l'uno o l'altro         *
    # ___                                  *
    #--------------------------------------*
    if($cog_nom && $rag_soc eq "???")
    {
        $rag_soc = $cog_nom               ;
    }
    #--------------------------------------*
    # Data documento                       *
    #--------------------------------------*
       $pmt_doc = $data->{FatturaElettronicaBody}
                       ->{DatiGenerali}
                       ->{DatiGeneraliDocumento};
    my $dat_doc = $pmt_doc->{Data}        ;
    #--------------------------------------*
    # Numero documento                     *
    #--------------------------------------*
       $pmt_doc = $data->{FatturaElettronicaBody}
                       ->{DatiGenerali}
                       ->{DatiGeneraliDocumento};
    my $num_doc = $pmt_doc->{Numero}      ;
    #--------------------------------------*
    # Valori restituiti                    *
    #--------------------------------------*
    my @val_dat                           ;
    push (@val_dat, $prt_iva)             ;
    push (@val_dat, $dat_doc)             ;
    push (@val_dat, $num_doc)             ;
    push (@val_dat, $rag_soc)             ;
    return @val_dat                       ;
    #--------------------------------------*
    # Fine subroutine 'rea_doc'            *
    #======================================*
}

#=========================================*
# Trattamento date in input               *
#-----------------------------------------*
sub dat_inp
{
    #-------------------------------------*
    # Valore in input                     *
    #-------------------------------------*
    my $date = shift                      ;
    #-------------------------------------*
    # Scomposizione data                  *
    #-------------------------------------*
    my $ann = substr($date, 0, 3)         ;
       $ann = $ann+1900                   ;
       $ann = sprintf("%04d",$ann)        ;
    my $mes = substr($date, 3, 2)         ;
       $mes = sprintf("%02d",$mes)        ;
    my $gio = substr($date, 5, 2)         ;
       $gio = sprintf("%02d",$gio)        ;
    my $out = $ann
            . "-"
            . $mes
            . "-"
            . $gio                        ;
    #--------------------------------------*
    # Valore restituito                    *
    #======================================*
    return $out                           ;
}

#=========================================*
# Trattamento date in output              *
#-----------------------------------------*
sub dat_out
{
    #-------------------------------------*
    # Valore in input                     *
    #-------------------------------------*
    my $dato = shift                      ;
    #-------------------------------------*
    # Data - formato TANGRAM              *
    #-------------------------------------*
    my @dats = split(/-/, $dato)          ;
    my $gior = $dats[2]                   ;
    my $mese = $dats[1]                   ;
    my $anno = $dats[0]-1900              ;
    my $dout = $anno . $mese . $gior      ;
    #--------------------------------------*
    # Valore restituito                    *
    #======================================*
    return $dout                          ;
}

#==========================================*
# Confronto date                           *
#------------------------------------------*
sub dat_cnf
{
    #--------------------------------------*
    # Date in input                        *
    #--------------------------------------*
    my $dat_001 = shift                   ;
    my $dat_002 = shift                   ;
    #--------------------------------------*
    # Confronto delle date                 *
    #--------------------------------------*
    my $date1 = ParseDate($dat_001)       ;
    my $date2 = ParseDate($dat_002)       ;
    my $flag = Date_Cmp($date1,$date2)    ;
    #--------------------------------------*
    # Valore restituito                    *
    #======================================*
    return $flag                          ;
}

