#!/bin/sh
#
# Convertitore PDF --> JPEG funzionante
#
# ESEMPIO DI UTILIZZO:
# ./pdf2jpg /abd/asc/master/pdf/out/fat300.pdf fat300_prova.jpg > /dev/null
#

# Pathname in input (PDF)
PTH_INP=$1;

# Pathname in output (JPEG)
PTH_OUT=$2;

# Risoluzione
RES_IMG="300x300";

# Richiamo di GhostScript
gs -sDEVICE=jpeg -sOutputFile="$PTH_OUT" -dNOPAUSE -r"$RES_IMG" -dBATCH "$PTH_INP";