#!/usr/bin/perl -w
# Legge da HTTP, scrive su file e invia tramite FTP

use LWP 5.64;
  my $url = 'https://florissima.dyndns.org/florissima/getimage?class=de.florissima.data.erp.items.FlArtikel&id=101048019&thumbnail=false/';   # Yes, HTTPS!
  my $browser = LWP::UserAgent->new;
  my $response = $browser->get($url);
  die "Error at $url\n ", $response->status_line, "\n Aborting"
   unless $response->is_success;
  print "Whee, it worked!  I got that ",
   $response->content_type, " document!\n";


my($code, $mess, %h) = $s->read_response_headers;

open (IMMAGINE, ">/abd/asc/tmp/florissima.jpg") or die
         "Impossibile aprire il file Immagine";

while (1) {
   my $buf;
   my $n = $s->read_entity_body($buf, 1024);
   die "read failed: $!" unless defined $n;
   last unless $n;
   print IMMAGINE $buf;   
}

close IMMAGINE;
