#!/usr/bin/perl -w

# NON FUNSIA !!!!!

use strict;
use WWW::Mechanize;
use HTTP::Cookies;

my $url = "www.linksimprese.sanpaoloimi.com/pmiweb/LoginServlet";
my $username = "C00AG900";
my $password = "";
my $mech = WWW::Mechanize->new();
$mech->cookie_jar(HTTP::Cookies->new());
$mech->get($url);
$mech->form_name('frmLogin');
$mech->field(RTLPBJSRNAPUI1RFZk1Q3A0QGSMHPXxX => $username);
$mech->field(WTC0xCXPkBPRKHEN0IxMPT2KPGA2SKRX => $password);
$mech->click();

