#!/usr/bin/perl -w
#==========================================*
# Modulo Perl di invio posta Mail::Sender  *
#                                          *
# t_sender_test                            *
#                                          *
#------------------------------------------*

#==========================================*
# Moduli Perl utilizzati                   *
#------------------------------------------*
use Mail::Sender                          ;

my $host = 'smtp.guttadauro.net'          ;
my $mitt = 'fatture@elettromat.it'        ;
my $dest = 'dkb@dkb.it'                   ;
my $user = 'fatture@elettromat.it'        ;
my $pass = 'fastway'                      ;
my $send = ''                             ;

if ($send = new Mail::Sender({
   smtp => $host,
   from => $mitt,
   to => $dest,
   subject => 'Messaggio di prova t_sender',
   msg => "Prova dal server\nArrivata?",
   auth => 'NTLM',
   authid => $user,
   authpwd => $pass,
 }) < 0) {
  die "$Mail::Sender::Error\n";
 }
 print "Mail sent OK.\n"
